name: Equidei CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    #- run: pm2 kill
    #- run: pm2 start index.js
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.KEY }}
        host: 3.108.234.188
        username: ubuntu
        port: 22
        source: "*"
        target: "/home/ubuntu/equidei-backend/"
         
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.KEY }}
        host: 3.108.234.188
        username: ubuntu
        port: 22
        script: |
          ls
          cd equidei-backend
          npm i
          pm2 restart index.js
        #proxy_port: 8000
        
       
    

